PREFIX sari: <https://platform.swissartresearch.net/>
PREFIX search: <https://platform.swissartresearch.net/search/>
PREFIX : <http://www.metaphacts.com/resource/>
PREFIX crmdig: <http://www.ics.forth.gr/isl/CRMdig/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX gndo: <https://d-nb.info/standards/elementset/gnd#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX frbroo: <http://iflastandards.info/ns/fr/frbr/frbroo/>

DROP GRAPH sari:relations;

INSERT {
  GRAPH sari:relations {
    ?place crm:P89_falls_within ?parentPlace .
  }
}WHERE {
  ?gndPlace gndo:geographicAreaCode ?gndParentPlace .
  ?place crmdig:L54_is_same-as ?gndPlace .
  ?parentPlace crmdig:L54_is_same-as ?gndParentPlace .
};

INSERT DATA {
  GRAPH sari:relations {
    search:Entity a rdfs:Class ;
      rdfs:equivalentClass crm:E1_CRM_Entity ;
      rdfs:label 'Search Entity' .
    search:Object rdfs:label 'Object' ;
      a rdfs:Class ;
      rdfs:subClassOf search:Entity ;
      rdfs:equivalentClass crm:E22_Human-Made_Object .
    search:Person rdfs:label 'Person' ;
      a rdfs:Class ;
      rdfs:subClassOf search:Entity ;
      rdfs:equivalentClass crm:E39_Actor .
    search:Place rdfs:label 'Place'  ;
      a rdfs:Class ;
      rdfs:subClassOf search:Entity ;
      rdfs:equivalentClass crm:E53_Place .
    search:Type rdfs:label 'Type' ;
      a rdfs:Class ;
      rdfs:subClassOf search:Entity ;
      rdfs:equivalentClass crm:E55_Type .
  }
};
 
INSERT {
  GRAPH sari:relations {
      ?subject a search:Person .
  }
} WHERE {
  VALUES(?actor_or_person) {
    (crm:E39_Actor)
    (crm:E21_Person)
    (crm:E74_Group)
  }
  ?subject a ?actor_or_person .
  FILTER(REGEX(STR(?subject), 'swissartresearch.net'))
};

INSERT {
  GRAPH sari:relations {
    ?subject a search:Type .
  }
} WHERE {
  ?subject a crm:E55_Type
  FILTER(REGEX(STR(?subject), 'swissartresearch.net'))
};

INSERT {
  GRAPH sari:relations {
    ?subject a search:Place .
  }
} WHERE {
  ?subject a crm:E53_Place
  FILTER(REGEX(STR(?subject), 'swissartresearch.net'))
  FILTER NOT EXISTS {
    GRAPH <https://resource.swissartresearch.net/graph/smapshot> {
      ?subject a crm:E53_Place .
    }
  }
};

INSERT {
  GRAPH sari:relations {
    ?subject a search:Object .
  }
} WHERE {
  ?subject a crm:E22_Human-Made_Object
  FILTER(REGEX(STR(?subject), 'swissartresearch.net/artwork'))
};

INSERT {
  GRAPH sari:relations {
    ?subject dcterms:date ?value .
  }
} WHERE {
  ?subject a search:Object;
    (crm:P108i_was_produced_by|(crm:P128_carries/crm:P94i_was_created_by))/crm:P4_has_time-span ?date .
  OPTIONAL {
    ?date crm:P82a_begin_of_the_begin ?date_value_begin .
  }
  OPTIONAL {
    ?date crm:P82b_end_of_the_end ?date_value_end .
  }
  BIND(IF(BOUND(?date_value_begin), ?date_value_begin, ?date_value_end) AS ?value)
};

INSERT {
	GRAPH ?g {
      ?event crm:P14_carried_out_by ?actor .
  }
} WHERE {
  GRAPH ?g {
    ?event crm:P9_consists_of ?subevent .
    ?subevent crm:P14_carried_out_by ?actor .
    FILTER NOT EXISTS { ?event crm:P14_carried_out_by ?actor . }
  }
};

INSERT {
  GRAPH ?g {
    ?entity crm:P94i_was_created_by ?creation .
  }
} WHERE {
  GRAPH ?g {
    ?entity frbroo:R24i_was_created_through ?creation .
  }
};