DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
} WHERE {
  GRAPH ?g {
    ?s ?p ?o
   }
  FILTER(REGEX(STR(?g), 'http://platform.swissartresearch.net/instances/fields/') )
};
DELETE {
  ?s ?p1 ?o1 .
  ?s1 ?p2 ?s .
} WHERE {
  <http://www.metaphacts.com/ontologies/platform#fieldDefinitionContainer> <http://www.w3.org/ns/ldp#contains> ?s .
  ?s ?p1 ?o1 .
  ?s1 ?p2 ?s .
};
DROP GRAPH <http://www.metaphacts.com/ontologies/platform#fieldDefinitionContainer>