version: "3"
services:
  blazegraph:
    healthcheck:
      test: wget -q -s http://0.0.0.0:8080/blazegraph/sparql?query=SELECT%20%3Fs%20WHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo%20%0A%7D%20LIMIT%2010 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 2
      start_period: 40s
    networks:
    - internal

  jobs:
    networks:
    - internal

  platform:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 8080
    networks:
    - internal
    - proxy
  
  smapshotapi:
    networks:
    - internal

networks:
  internal:
  proxy:
    external:
      name: nginx_proxy_network
