version: "3"
services:

  blazegraph:
    image: metaphacts/blazegraph-basic
    container_name: ${PROJECT_NAME}_blazegraph
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx4g
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - blazegraph-data:/blazegraph-data
      - ./data:/data

  jobs:
    build: ./services/jobs
    container_name: ${PROJECT_NAME}_jobs
    image: swissartresearx/bso-jobs:1.0.0
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./mapping:/mapping
      - ./scripts:/scripts
      - ./static:/static
      - ./services/researchplatform/apps/bso/src:/bso-app-src

  platform:
    image: swissartresearx/metaphacts-community:4.1.2
    container_name: ${PROJECT_NAME}_platform
    restart: unless-stopped
    depends_on:
      - blazegraph
      - smapshotapi
    environment:
      - JAVA_OPTS=-Xmx1g
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - platform-data:/runtime-data
      - ./services/researchplatform/apps:/apps

  smapshotapi:
    build: ./services/smapshotapi
    container_name: ${PROJECT_NAME}_smapshotapi
    image: swissartresearx/bso-smapshotapi:1.0.3
    environment:
      - SMAPSHOT_ENDPOINT=${SMAPSHOT_ENDPOINT}
      - SMAPSHOT_TOKEN=${SMAPSHOT_TOKEN}
      - SPARQL_ENDPOINT=http://blazegraph:8080/blazegraph/sparql
      - SMAPSHOT_NAMEDGRAPH=${SMAPSHOT_IMAGE_GRAPH}
    restart: unless-stopped
    volumes:
      - ./services/smapshotapi/src:/src
        
volumes:
  3m-data:
  3m-db:
  blazegraph-data:
  platform-data:
  
