version: "3.4"
services:

  3m:
    image: swissartresearx/3m-docker:latest
    container_name: ${PROJECT_NAME}_3m
    environment:
      - IP_ADDRESS=0.0.0.0
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
       - 3m-db:/opt/exist/webapp/WEB-INF/data
       - 3m-data:/opt/3M
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  3m-data:
  3m-db:
