version: "3"
services:
  blazegraph:
    networks:
    - internal

  jobs:
    networks:
    - internal

  platform:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 8080
    networks:
    - internal
    - proxy
  
  smapshotapi:
    networks:
    - internal

networks:
  internal:
  proxy:
    external:
      name: nginx_proxy_network
