version: "3"
services:
  platform:
    environment:
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_HOST: ${HOST_NAME}
      VIRTUAL_HOST: ${HOST_NAME}
      VIRTUAL_PORT: 8080
    networks:
    - proxy

networks:
  proxy:
    external:
      name: saringinx_proxy_network