version: "3"
services:

  blazegraph:
    image: metaphacts/blazegraph-basic
    container_name: ${PROJECT_NAME}_blazegraph
    environment:
      - JAVA_OPTS=-Xmx1g
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - blazegraph-data:/blazegraph-data
      - ./data:/data

  jobs:
    build: ./services/jobs
    container_name: ${PROJECT_NAME}_jobs
    volumes:
      - ./data:/data
      - ./mapping:/mapping
      - ./scripts:/scripts
      - ./services/researchplatform/apps/bso/src:/bso-app-src

  platform:
    image: metaphacts/metaphactory:3.6.0
    container_name: ${PROJECT_NAME}_platform
    depends_on:
      - blazegraph
    environment:
      - JAVA_OPTS=-Xmx1g
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - platform-data:/runtime-data
      - ./services/researchplatform/apps:/apps

  proxy:
    build: ./services/proxy
    container_name: ${PROJECT_NAME}_proxy
    depends_on:
      - platform
      - blazegraph
    ports:
      - $PORT_PROXY:80

  researchspace:
    image: researchspace/platform-ci
    container_name: ${PROJECT_NAME}_researchspace
    restart: unless-stopped
    ports:
      - $PORT_RESEARCHSPACE:8080
    environment:
      PLATFORM_OPTS: >-
        -Dconfig.environment.sparqlEndpoint=http://blazegraph:8080/blazegraph/sparql
        -Dlog4j.configurationFile=classpath:org/researchspace/logging/log4j2.xml
        -Dconfig.storage.images.type=nonVersionedFile
        -Dconfig.storage.images.mutable=true
        -Dconfig.storage.images.root=/images
        -Dconfig.storage.tmp.type=nonVersionedFile
        -Dconfig.storage.tmp.mutable=true
        -Dconfig.storage.tmp.root=/tmp-data
    volumes:
       - researchspace-images:/images:rw
       - researchspace-temp:/tmp-data:rw
       - researchspace-data:/runtime-data
       - ./services/researchspace/apps:/apps
    depends_on:
      - blazegraph
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
        
volumes:
  3m-data:
  3m-db:
  blazegraph-data:
  platform-data:
  researchspace-data:
  researchspace-images:
  researchspace-temp:
  
