#!/bin/bash
source .env
REPO=swiss-art-research-net/bso-data

download () {
  repo=$1
  remotepath=$2
  localpath=$3

  echo -n "Downloading $remotepath: "
  python3 scripts/getFileContentsFromGit.py $GITHUB_USERNAME $GITHUB_PERSONAL_ACCESS_TOKEN $repo $remotepath $localpath
}

download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-100-a_d.csv" "data/source/zbz-curation-100-a_d.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-110-a.csv" "data/source/zbz-curation-110-a.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-264-a.csv" "data/source/zbz-curation-264-a.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-264-b.csv" "data/source/zbz-curation-264-b.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-340-a.csv" "data/source/zbz-curation-340-a.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-300-b.csv" "data/source/zbz-curation-300-b.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-600-a_b.csv" "data/source/zbz-curation-600-a_b.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-610-a_g.csv" "data/source/zbz-curation-610-a_g.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-611-a_c_d.csv" "data/source/zbz-curation-611-a_c_d.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-650-a_g.csv" "data/source/zbz-curation-650-a_g.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-651-a_g.csv" "data/source/zbz-curation-651-a_g.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-655-a.csv" "data/source/zbz-curation-655-a.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-700-a_d.csv" "data/source/zbz-curation-700-a_d.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-710-a.csv" "data/source/zbz-curation-710-a.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-751-a_g.csv" "data/source/zbz-curation-751-a_g.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-curation-relators.csv" "data/source/zbz-curation-relators.csv"
download "swiss-art-research-net/bso-data" "data/zbz/zbz-corrections.csv" "data/source/zbz-corrections.csv"
download "swiss-art-research-net/bso-data" "data/zbz/source/dois.csv" "data/source/zbz-dois.csv"
download "swiss-art-research-net/bso-data" "data/zbz/source/BIBLIOGRAPHIC_8971984070005508_1.xml" "data/source/BIBLIOGRAPHIC_8971984070005508_1.xml"
download "swiss-art-research-net/bso-data" "data/zbz/source/BIBLIOGRAPHIC_8971984070005508_2.xml" "data/source/BIBLIOGRAPHIC_8971984070005508_2.xml"
download "swiss-art-research-net/bso-data" "data/zbz/source/BIBLIOGRAPHIC_8971984070005508_3.xml" "data/source/BIBLIOGRAPHIC_8971984070005508_3.xml"
download "swiss-art-research-net/bso-data" "data/zbz/source/BIBLIOGRAPHIC_8971984070005508_4.xml" "data/source/BIBLIOGRAPHIC_8971984070005508_4.xml"
download "swiss-art-research-net/bso-data" "data/zbz/source/BIBLIOGRAPHIC_8972912360005508_1.xml" "data/source/BIBLIOGRAPHIC_8972912360005508_1.xml"

download "swiss-art-research-net/bso-data" "data/nb/nb-curation-personen.csv" "data/source/nb-curation-personen.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-geografika.csv" "data/source/nb-curation-geografika.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-koerperschaften.csv" "data/source/nb-curation-koerperschaften.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-names.csv" "data/source/nb-curation-names.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-roles.csv" "data/source/nb-curation-roles.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-extracted-levels.csv" "data/source/nb-curation-extracted-levels.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-curation-extracted-types.csv" "data/source/nb-curation-extracted-types.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-external-descriptors.csv" "data/source/nb-external-descriptors.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-image-sizes.csv" "data/source/nb-image-sizes.csv"
download "swiss-art-research-net/bso-data" "data/nb/nb-additional-images.csv" "data/source/nb-additional-images.csv"
download "swiss-art-research-net/bso-data" "data/nb/source/WMC_Records_20201201.xml" "data/source/nb-records.xml"
download "swiss-art-research-net/bso-data" "data/nb/source/Gugelman.xml" "data/source/nb-parentrecords.xml"

download "swiss-art-research-net/bso-data" "data/sff/Werke.csv" "data/source/sff-werke.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-werk-masse.csv" "data/source/sff-werk-masse.csv"
download "swiss-art-research-net/bso-data" "data/sff/source/Literatur.csv" "data/source/sff-literatur.csv"
download "swiss-art-research-net/bso-data" "data/sff/source/Literatur_index_Verknupfung.csv" "data/source/sff-literatur-links.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-images.csv" "data/source/sff-images.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-keywords.csv" "data/source/sff-curation-keywords.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-ortsbezug.csv" "data/source/sff-curation-ortsbezug.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-material.csv" "data/source/sff-curation-material.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-technik.csv" "data/source/sff-curation-technik.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-literature-in-zeitschrift.csv" "data/source/sff-curation-literature-in-zeitschrift.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-literature-ort.csv" "data/source/sff-curation-literature-ort.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-literature-verlag.csv" "data/source/sff-curation-literature-verlag.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-curation-literature-autor-hsg.csv" "data/source/sff-curation-literature-autor-hsg.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-artists.csv" "data/source/sff-artists.csv"
download "swiss-art-research-net/bso-data" "data/sff/sff-series.csv" "data/source/sff-series.csv"

download "swiss-art-research-net/bso-data" "data/sari/prefLabels.trig" "data/ttl/additional/prefLabels.trig"
download "swiss-art-research-net/bso-data" "data/sari/datasetMetadata.trig" "data/ttl/additional/datasetMetadata.trig"
download "swiss-art-research-net/bso-data" "data/sari/smapshot-classifications.trig" "data/ttl/additional/smapshot-classifications.trig"
download "swiss-art-research-net/bso-data" "data/sari/smapshot-identifiers.trig" "data/ttl/additional/smapshot-identifiers.trig"
download "swiss-art-research-net/bso-data" "data/sari/bso-roles-alignment.trig" "data/ttl/additional/bso-roles-alignment.trig"

download "swiss-art-research-net/bso-data" "data/sari/imageRegions.trig" "data/graphs/imageRegions.trig"
download "swiss-art-research-net/bso-big-data" "similarities/titleSimilarities.ttl" "data/graphs/titleSimilarities.ttl"
download "swiss-art-research-net/bso-big-data" "similarities/visualSimilarities.ttl" "data/graphs/visualSimilarities.ttl"
download "swiss-art-research-net/bso-big-data" "color-schemes/color_schemes_local_ordered.ttl" "data/graphs/colorSchemes.ttl"

download "swiss-art-research-net/bso-big-data" "distances/actors/birth_date_dist.ttl" "data/graphs/distances-birth_date_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/birth_years_dist.ttl" "data/graphs/distances-birth_years_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/creation_role_dist.ttl" "data/graphs/distances-creation_role_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/creations_dist.ttl" "data/graphs/distances-creations_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/death_date_dist.ttl" "data/graphs/distances-death_date_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/death_years_dist.ttl" "data/graphs/distances-death_years_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/labels_dist.ttl" "data/graphs/distances-labels_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/production_dist.ttl" "data/graphs/distances-production_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/production_obj_dist.ttl" "data/graphs/distances-production_obj_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/production_role_dist.ttl" "data/graphs/distances-production_role_dist.ttl"
download "swiss-art-research-net/bso-big-data" "distances/actors/visitem_dist.ttl" "data/graphs/distances-visitem_dist.ttl"

download "swiss-art-research-net/bso-data" "data/sari/bso-vocabulary.trig" "data/ttl/additional/bso-vocabulary.trig"
download "swiss-art-research-net/bso-data" "data/sari/additional-dates/external.ttl" "data/ttl/additional/additional-dates-external.ttl"
download "swiss-art-research-net/bso-data" "data/sari/additional-dates/nb.ttl" "data/ttl/additional/additional-dates-nb.ttl"
download "swiss-art-research-net/bso-data" "data/sari/additional-dates/sff.ttl" "data/ttl/additional/additional-dates-sff.ttl"
download "swiss-art-research-net/bso-data" "data/sari/additional-dates/zbz.ttl" "data/ttl/additional/additional-dates-zbz.ttl"

download "swiss-art-research-net/bso-data" "data/bso-thesaurus/bso-thesaurus.trig" "data/ttl/additional/bso-thesaurus.trig"
download "swiss-art-research-net/bso-data" "data/additional/aat-events.ttl" "data/ttl/additional/aat-events.ttl"
download "swiss-art-research-net/bso-data" "data/additional/swisstopo-cantons.trig" "data/ttl/additional/swisstopo-cantons.trig"
download "swiss-art-research-net/bso-data" "data/additional/swisstopo-municipalities.trig" "data/ttl/additional/swisstopo-municipalities.trig"
download "swiss-art-research-net/bso-data" "data/additional/swisstopo-districts.trig" "data/ttl/additional/swisstopo-districts.trig"