DELETE {
  GRAPH ?g {
    ?s ?p ?o
  }
} WHERE {
  GRAPH ?g {
    ?s ?p ?o
   }
  FILTER(REGEX(STR(?g), "http://rs.swissartresearch.net/instances/fields/") )
};
DROP GRAPH <http://www.metaphacts.com/ontologies/platform#fieldDefinitionContainer>;